#!/usr/bin/python
import sys
from wq.app.util.build import Builder


def usage():
    print """Usage: wq [command] [version] [configfile]"

Valid commands:
   appcache
   build
   collectjson
   init
   optimize
   scss
   setversion
"""

if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else ""
    if len(sys.argv) > 2:
        args = sys.argv[2:]
    else:
        args = []
    if cmd == "":
        usage()
        exit()

    builder = Builder(*args)
    fn = getattr(builder, cmd, None)
    if fn is not None:
        fn()
    else:
        usage()
